- name: Run scraper
        run: python fetch_videos.py

      - name: Check if file exists
        run: ls -l movie_links.txt # 如果這裡報錯，代表 Python 沒成功寫入檔案

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add movie_links.txt
          # 加上 || echo 避免因為沒有內容更新而導致整個 Workflow 失敗
          git commit -m "Update links: $(date)" || echo "No changes to commit"
          git push
